# Generated by Django 3.0.8 on 2020-07-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('int_code', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('credit', models.PositiveIntegerField(default=0)),
                ('followers', models.ManyToManyField(related_name='follows', to='anivamSite.Person')),
                ('followings', models.ManyToManyField(related_name='followis', to='anivamSite.Person')),
            ],
        ),
    ]
