# Generated by Django 3.0.8 on 2020-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anivamSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='followers',
            field=models.ManyToManyField(related_name='follows', to='anivamSite.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='followings',
            field=models.ManyToManyField(related_name='followis', to='anivamSite.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='int_code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
