# Generated by Django 3.0.8 on 2020-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anivamSite', '0002_auto_20200726_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follows', to='anivamSite.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followis', to='anivamSite.Person'),
        ),
    ]
